version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "share-data"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c9qzg9d1iqw"
s3_prefix = "share-data"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
